#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Section for git-secrets
if ! command -v detect-secrets &> /dev/null
then
    echo "detect-secrets is not installed."
    exit 1
fi

echo "Running detect-secrets..."
# Scans the commit message.
detect-secrets scan --no-verify --string "$@"
