#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if detect-secrets is installed
if ! command -v detect-secrets &> /dev/null
then
    echo "detect-secrets is not installed."
    exit 1
fi

echo "Running detect-secrets..."
# Scans the commit message.
detect-secrets scan --no-verify --word-list wordlist.txt --string "$@" > /dev/null
