name: QLTY Code Coverage

on: [push, pull_request]

permissions:
  contents: read
  id-token: write

jobs:
  coverage:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node: [22.x, 24.x, 26.x]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/lcov.info
